# Advent of Code 2022 - Day 8

In [23]:
from pathlib import Path
from typing import List, Dict, Set, Tuple, Any
import numpy as np

## Part One



Read input

In [24]:
def read_input(input_name: str) -> List[str]:
    input_path = Path.cwd() / "input" / input_name

    with open(input_path, 'r') as input_file:
        
        lines = input_file.readlines()
        
    return [line.rstrip("\n") for line in lines]

In [25]:
tree_lines_test = read_input("day8_input_test.txt")
tree_lines = read_input("day8_input.txt")

TREE_LINES = tree_lines_test

Convert each line in to a list of ints

In [26]:
def str_to_int_list(line: str) -> List[int]:

    return [int(char) for char in line]


def tree_line_to_matrix(line_list: List[str]) -> List[List[int]]:

    list_matrix = [str_to_int_list(line) for line in line_list]

    return np.matrix(list_matrix)

In [27]:
tree_matrix = tree_line_to_matrix(TREE_LINES)

In [28]:
tree_matrix

matrix([[3, 0, 3, 7, 3],
        [2, 5, 5, 1, 2],
        [6, 5, 3, 3, 2],
        [3, 3, 5, 4, 9],
        [3, 5, 3, 9, 0]])

### Using `np.diff()`

`np.diff(tree_matrix, axis=X)` will return an array that has one less row or column (depending on axis) than then input matrix --> This will always be an 'edge' so it does not matter.

If a value in the return is >0 then that tree is taller than the one next to it on the axis specified.

In [29]:
np.diff(tree_matrix, axis=0) > 0

matrix([[False,  True,  True, False, False],
        [ True, False, False,  True, False],
        [False, False,  True,  True,  True],
        [False,  True, False,  True, False]])

In [49]:
inner_truth_matrix = np.logical_or(
    np.diff(tree_matrix, axis=0)[:-1, 1:-1] > 0,  # Along columns
    np.diff(tree_matrix, axis=1)[1:-1, :-1] > 0,
)  # Along rows
inner_flipped_truth_matrix = np.logical_or(
    np.diff(np.flipud(tree_matrix), axis=0)[:-1,1:-1] > 0,
    np.diff(np.fliplr(tree_matrix), axis=1)[1:-1, :-1] > 0,
)

In [50]:
inner_truth_matrix

matrix([[ True,  True, False],
        [False, False,  True],
        [False,  True,  True]])

In [51]:
inner_flipped_truth_matrix

matrix([[False,  True, False],
        [ True, False,  True],
        [False,  True, False]])

In [52]:
np.logical_or(inner_truth_matrix, inner_flipped_truth_matrix)

matrix([[ True,  True, False],
        [ True, False,  True],
        [False,  True,  True]])

Total number of trees is all edge trees plus the sum of the truth matrix

In [ ]:
total_trees = (
    tree_matrix.shape[0] * 2 + (tree_matrix.shape[1] - 2) * 2 + inner_truth_matrix.sum()
)
total_trees

21

### Another method?