# Advent of Code 2022 - Day 8

In [2]:
from pathlib import Path
from typing import List, Dict, Set, Tuple, Any
import numpy as np

## Part One



Read input

In [3]:
def read_input(input_name: str) -> List[str]:
    input_path = Path.cwd() / "input" / input_name

    with open(input_path, 'r') as input_file:
        
        lines = input_file.readlines()
        
    return [line.rstrip("\n") for line in lines]

In [4]:
tree_lines_test = read_input("day8_input_test.txt")
tree_lines = read_input("day8_input.txt")

TREE_LINES = tree_lines_test

Convert each line in to a list of ints

In [5]:
def str_to_int_list(line: str) -> List[int]:

    return [int(char) for char in line]


def tree_line_to_matrix(line_list: List[str]) -> List[List[int]]:

    list_matrix = [str_to_int_list(line) for line in line_list]

    return np.matrix(list_matrix)

In [6]:
tree_matrix = tree_line_to_matrix(TREE_LINES)

In [7]:
tree_matrix

matrix([[3, 0, 3, 7, 3],
        [2, 5, 5, 1, 2],
        [6, 5, 3, 3, 2],
        [3, 3, 5, 4, 9],
        [3, 5, 3, 9, 0]])

### Using `np.diff()`

`np.diff(tree_matrix, axis=X)` will return an array that has one less row or column (depending on axis) than then input matrix --> This will always be an 'edge' so it does not matter.

If a value in the return is >0 then that tree is taller than the one next to it on the axis specified.

In [8]:
np.diff(tree_matrix, axis=0) > 0

matrix([[False,  True,  True, False, False],
        [ True, False, False,  True, False],
        [False, False,  True,  True,  True],
        [False,  True, False,  True, False]])

In [9]:
from_top = np.diff(tree_matrix, axis=0)[:-1, 1:-1] > 0
from_left = np.diff(tree_matrix, axis=1)[1:-1, :-1] > 0
from_bottom = np.flipud(np.diff(np.flipud(tree_matrix), axis=0)[:-1,1:-1]) > 0
from_right = np.fliplr(np.diff(np.fliplr(tree_matrix), axis=1)[1:-1, :-1]) > 0

In [11]:
from_top

matrix([[ True,  True, False],
        [False, False,  True],
        [False,  True,  True]])

In [12]:
from_left

matrix([[ True, False, False],
        [False, False, False],
        [False,  True, False]])

In [13]:
from_bottom

matrix([[False,  True, False],
        [ True, False, False],
        [False,  True, False]])

In [14]:
from_right

matrix([[False,  True, False],
        [ True, False,  True],
        [False,  True, False]])

In [15]:
inner_truth_matrix = np.logical_or(
    np.diff(tree_matrix, axis=0)[:-1, 1:-1] > 0,  # Along columns
    np.diff(tree_matrix, axis=1)[1:-1, :-1] > 0,
)  # Along rows
inner_flipped_truth_matrix = np.logical_or(
    np.flipud(np.diff(np.flipud(tree_matrix), axis=0)[:-1,1:-1]) > 0,
    np.fliplr(np.diff(np.fliplr(tree_matrix), axis=1)[1:-1, :-1]) > 0,
)

In [16]:
np.logical_or(inner_truth_matrix, inner_flipped_truth_matrix)

matrix([[ True,  True, False],
        [ True, False,  True],
        [False,  True,  True]])

Total number of trees is all edge trees plus the sum of the truth matrix

In [17]:
total_trees = (
    tree_matrix.shape[0] * 2 + (tree_matrix.shape[1] - 2) * 2 + inner_truth_matrix.sum()
)
total_trees

21

### Another method?

Iterate through 'inner' square, checking 4 cells around it using slicing

In [18]:
def check_around()

5

In [19]:
def evolve(grid, dt, D=1.0):
    if not isinstance(grid, np.ndarray): #ensuring that is a numpy array.
        grid = np.array(grid)
    u_grid = np.roll(grid, 1, axis=0)
    d_grid = np.roll(grid, -1, axis=0)
    r_grid = np.roll(grid, 1, axis=1)
    l_grid = np.roll(grid, -1, axis=1)
    new_grid = grid + D * (u_grid + d_grid + r_grid + l_grid - 4.0*grid) * dt
    return new_grid

In [23]:
tree_matrix

matrix([[3, 0, 3, 7, 3],
        [2, 5, 5, 1, 2],
        [6, 5, 3, 3, 2],
        [3, 3, 5, 4, 9],
        [3, 5, 3, 9, 0]])

In [22]:
np.roll(tree_matrix, 1, axis=0)

matrix([[3, 5, 3, 9, 0],
        [3, 0, 3, 7, 3],
        [2, 5, 5, 1, 2],
        [6, 5, 3, 3, 2],
        [3, 3, 5, 4, 9]])

In [27]:
tree_array = np.array([2,5,5,1,2])
tree_array

array([2, 5, 5, 1, 2])

In [28]:
np.diff(tree_array)

array([ 3,  0, -4,  1])